### ISSUE TITLE
Support global call

### ISSUE THREAD

**Issue by turbo8p** [crazyfactory/aws-sts-helper#1]
## Problem
It would make the script way easier to use if it can run from anywhere.

Currently, the constraint is in the `assume_role.sh` which depends on `setup.sh`
This dependency make global script call impossible. I tried to symlink it and make it globally accessible like below
```
sudo ln -s /home/ec2-user/aws-sts-helper/assume-role.sh /usr/local/bin/assume_role
sudo ln -s /home/ec2-user/aws-sts-helper/get-session-token.sh /usr/local/bin/get_session_token
```
But when call the script `assume_role`, it complains that it cannot find `setup.sh`

**Comment by dacgray** [comment]
Should be able to do something like this: https://stackoverflow.com/questions/24112727/relative-paths-based-on-file-location-instead-of-current-working-directory

**Comment by dacgray** [comment]
Should be working for git bash in windows, and linux now.

Pls see readme for instructions.
